### ISSUE TITLE
Excessive load time for new Quarto and RMD documents in GCP Cloud Workstations

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio-docker-products#514] opened 2023-04-07 04:50 UTC
The first time a new Quarto or RMD document is opened from the IDE via the New File menu, it takes a very long time before the document finally opens. During the process, an error message sometimes appears that indicates trouble with `get_active_sessions`:

![image](https://user-images.githubusercontent.com/10444878/230543790-e112046d-9842-4b2d-9790-73f993f0e85a.png)

Subsequent new files load much more quickly once the first one has loaded.

**Comment by ianpittwood** [comment] 2023-04-19 21:19
@blairj09 I think these problems were caused by #516 which was preventing consistent communications with the Launcher service. I was able to create an RMD and Quarto doc without much delay. Could you test it out as well to make sure they're performing for you as well?

**Comment by blairj09** [comment] 2023-04-20 20:02
Observations testing with `ianprstudio/gcw-workbench:2022.03.0-6`:
* Quarto and RMD documents open very quickly!
* When I first opened a Quarto document, I saw the following error:  
![image](https://user-images.githubusercontent.com/10444878/233475215-c793a4f1-e9a4-40ad-89b6-06a0e226db30.png)
  Clicking "Ok" allowed me to continue working as expected, but I'm not sure what caused the error

**Comment by ianpittwood** [comment] 2023-04-25 21:25
I've been unable to replicate the 405 error you got, @blairj09. Since the performance issue itself is resolved, I'm going to close this issue. We can open a new issue if we encounter the 405 error (or any other RStudio error) in the future.

**Closed by ianpittwood** 2023-04-25 21:25 UTC
Labels: bug, gcw
