### ISSUE TITLE
JupyterLab doesn't load in GCP Cloud Workstations image

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio-docker-products#517] opened 2023-04-07 17:02 UTC
When launching JupyterLab from the GCP Cloud Workstations image, a blank page with a small Jupyter logo in the upper left-hand corner is the only thing that loads:
![image](https://user-images.githubusercontent.com/10444878/230648174-720cdab4-57b2-47db-8a65-092d7f7c924e.png)

**Comment by ianpittwood** [comment] 2023-04-11 21:54
I'm fairly certain this is an issue with whatever distributes the static content for workbench. I thought to check the console on my browser and found a slew of JS errors (see attached).

[gcw-jupyterlab-js-console-logs041123.txt](https://github.com/rstudio/rstudio-docker-products/files/11205269/gcw-jupyterlab-js-console-logs041123.txt)

**Comment by ianpittwood** [comment] 2023-04-14 16:36
I've still been unable to figure this out. I'm still thinking this is a problem caused by the URL redirects GCW is using with our Workbench container interfering with our ability to serve static content and make API calls. I've tried the following so far:
* Jupyter Config Options:
  * `allow_origin='*'` - No change, still see some CORS-related errors in the console
  * `allow_remote_access=True` - No change
  * `trust_xheaders=True` - No change
  * `use_redirect_file=False` - No change
* Test run outside of workbench
  * Ran `jupyter lab --no-browser --allow-root --ip=0.0.0.0 --port=8888` and accessed Jupyter Lab instance directly by replacing `80-workstation-workbench-gcar.cluster-wtveq2k5qveiurydwz3piwpyzu.cloudworkstations.dev/` with `8888-workstation-workbench-gcar.cluster-wtveq2k5qveiurydwz3piwpyzu.cloudworkstations.dev/` - No change, content still would not load
  * Ran above command with `gcloud` command for local port forwarding - **WORKS**

The only instance in which Jupyter Lab functioned correctly was when I port forwarded `localhost:8080` to the Jupyter Lab instance. When all the server calls run through `localhost` or `127.0.0.1`, everything seems to work fine so I would assume the installation is correct and working. Something in the configuration of Jupyter Lab is causing it not to serve correctly when accessed through the GCW URL.

Out of curiosity, I also tried port forwarding all of Workbench for GCW to `localhost:8080` and Jupyter Lab still worked that way too.

**Comment by ianpittwood** [comment] 2023-04-14 21:23
Through more digging, we found that this is some sort of collision between Jupyter Lab's auth and GCW's auth. By setting `--LabApp.token=""`, we were able to successfully start a one-off session of Jupyter Lab in GCW. Unfortunately, more work will be required as the same flag causes Workbench to hang on `STARTING` when launching Jupyter Lab.

**Comment by ianpittwood** [comment] 2023-04-19 21:15
rstudio/rstudio-pro#4568 fixed the problems with Workbench hanging on startup with the `--LabApp.token=""` flag set. We'll need to use a pre-release build of some sort in the intervening time before the next release or patch release.

**Comment by blairj09** [comment] 2023-04-20 19:57
Confirmed JupyterLab is working in `ianprstudio/gcw-workbench:2022.03.0-6`

**Comment by ianpittwood** [comment] 2023-04-25 21:24
While this has been temporarily fixed by using a daily build, the Workbench team expects to backport the fix for this issue to 2023.03.0. We can close this once the fix is backported and implemented in the image.

**Comment by ianpittwood** [comment] 2023-05-24 19:03
2023.03.1 was successfully implemented on Friday (5/19). JupyterLab was confirmed working and I haven't received any additional reports of problems.

**Closed by ianpittwood** 2023-05-24 19:03 UTC
Labels: bug, gcw
